version: '3'
services:
  admin-gateway:
    container_name: admin-gateway
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
  default:
    name: mine-network
